[workspace]
members = ["derives"]
resolver = "2"

[package]
name = "rioc"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
dashmap = "6.1"
ibag = { git = "https://github.com/open1s/ibag.git" }